I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 19, in script call
    call begin_TutRPG #Testing our Battle Mode
  File "game/rpgmode/battlemode.rpy", line 19, in script
    $renpy.pause (normal_settings.dialogue_pause)    #So we don't start doing dialogues
  File "game/rpgmode/battlemode.rpy", line 19, in <module>
    $renpy.pause (normal_settings.dialogue_pause)    #So we don't start doing dialogues
NameError: name 'normal_settings' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 19, in script call
    call begin_TutRPG #Testing our Battle Mode
  File "game/rpgmode/battlemode.rpy", line 19, in script
    $renpy.pause (normal_settings.dialogue_pause)    #So we don't start doing dialogues
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 881, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\python.py", line 1913, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/rpgmode/battlemode.rpy", line 19, in <module>
    $renpy.pause (normal_settings.dialogue_pause)    #So we don't start doing dialogues
NameError: name 'normal_settings' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SpIn 1.0
Sat Mar 09 18:15:33 2019
