I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 21, in script call
    call huntmodestart #Testing our hunt mode
  File "game/huntmode/hunt.rpy", line 173, in script call
    call huntmode
  File "game/huntmode/hunt.rpy", line 177, in script call
    call screen huntmodeset
  File "game/huntmode/hunt.rpy", line 191, in script
    plau audio "sfx/collect.mp3"
Exception: Sayer 'plau' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 21, in script call
    call huntmodestart #Testing our hunt mode
  File "game/huntmode/hunt.rpy", line 173, in script call
    call huntmode
  File "game/huntmode/hunt.rpy", line 177, in script call
    call screen huntmodeset
  File "game/huntmode/hunt.rpy", line 191, in script
    plau audio "sfx/collect.mp3"
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\J\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'plau' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
SpIn 1.0
Sun Apr 14 20:45:43 2019
